// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRK8sFTf60JXgf7bZCuqfgZK0eaJJsHcQ',
    appId: '1:934406621606:web:2e35911a1485cfd6e82767',
    messagingSenderId: '934406621606',
    projectId: 'e-commerce-app-669f8',
    authDomain: 'e-commerce-app-669f8.firebaseapp.com',
    storageBucket: 'e-commerce-app-669f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI1jzqSnTZNhJgaE_Vn603XbSNsfBLzqM',
    appId: '1:934406621606:android:1e6908477a9e48cae82767',
    messagingSenderId: '934406621606',
    projectId: 'e-commerce-app-669f8',
    storageBucket: 'e-commerce-app-669f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq_KXu63Yj68cKe0hTZ-sNJtEVZaedIo8',
    appId: '1:934406621606:ios:7a0d2414a40756a5e82767',
    messagingSenderId: '934406621606',
    projectId: 'e-commerce-app-669f8',
    storageBucket: 'e-commerce-app-669f8.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq_KXu63Yj68cKe0hTZ-sNJtEVZaedIo8',
    appId: '1:934406621606:ios:7a0d2414a40756a5e82767',
    messagingSenderId: '934406621606',
    projectId: 'e-commerce-app-669f8',
    storageBucket: 'e-commerce-app-669f8.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRK8sFTf60JXgf7bZCuqfgZK0eaJJsHcQ',
    appId: '1:934406621606:web:8b33303d93de114ce82767',
    messagingSenderId: '934406621606',
    projectId: 'e-commerce-app-669f8',
    authDomain: 'e-commerce-app-669f8.firebaseapp.com',
    storageBucket: 'e-commerce-app-669f8.appspot.com',
  );
}
