// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3UWW_kNV-5WWc0z9lGiGkCtAuUMkQ4Q',
    appId: '1:967298574291:web:1d393523bf0a3fd4de7126',
    messagingSenderId: '967298574291',
    projectId: 'e-commerce-2699c',
    authDomain: 'e-commerce-2699c.firebaseapp.com',
    storageBucket: 'e-commerce-2699c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdmvEHpc7dP4TxCpbA67X7NfxI-9er2Hc',
    appId: '1:967298574291:android:d3e767c00d1562a1de7126',
    messagingSenderId: '967298574291',
    projectId: 'e-commerce-2699c',
    storageBucket: 'e-commerce-2699c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgmLNBUKLK4aity4hewsa_BT5VQOLgSTk',
    appId: '1:967298574291:ios:8ca587a5700b91b2de7126',
    messagingSenderId: '967298574291',
    projectId: 'e-commerce-2699c',
    storageBucket: 'e-commerce-2699c.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgmLNBUKLK4aity4hewsa_BT5VQOLgSTk',
    appId: '1:967298574291:ios:8ca587a5700b91b2de7126',
    messagingSenderId: '967298574291',
    projectId: 'e-commerce-2699c',
    storageBucket: 'e-commerce-2699c.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq3UWW_kNV-5WWc0z9lGiGkCtAuUMkQ4Q',
    appId: '1:967298574291:web:53b218848115929dde7126',
    messagingSenderId: '967298574291',
    projectId: 'e-commerce-2699c',
    authDomain: 'e-commerce-2699c.firebaseapp.com',
    storageBucket: 'e-commerce-2699c.appspot.com',
  );

}