import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'injection.config.dart'; // This file will be generated

// 1. Create a global instance of GetIt
final getIt = GetIt.instance;

// 2. Mark this function to be generated by injectable
@InjectableInit(
  initializerName: 'init', // default
  preferRelativeImports: true, 
  asExtension: true, // generates getIt.init()
)
void configureDependencies() => getIt.init();